### ISSUE TITLE
Connection to server problem

### ISSUE THREAD

**Issue by sakul-thakuri-kr** [fabasoad/setup-cassandra-action#1]
I am not being able to connect to server with given port in example or localhost. please kindly provide details on how to set host here. what will be the host for cassandra in github action.

**Comment by fabasoad** [comment]
`host` is DNS name or public IP of a machine where cassandra is installed. Please share yaml code that you used, so I can help you.

**Comment by fabasoad** [comment]
Closing this ticket as a stale. @sakul-thakuri-kr if you have any questions or found any issues please open a new issue. Thank you.

**Comment by EduardoFLima** [comment]
Just had the same issue:

`Connection error: ('Unable to connect to any servers', {'192.168.176.3:9042': error(None, "Tried connecting to [('192.168.176.3', 9042)]. Last error: timed out")})`

Where `192.168.176.3:9042` is the ip:port of a cassandra container (which is working fine since I'm able to use for other purposes). Also tried to increase the timeout to 30 but still had the same issue.

**Comment by fabasoad** [comment]
@EduardoFLima is this IP publicly available? If yes, could you please check the access from GitHub Actions itself independently from this action? I mean just simple `ping` or `curl` to get the status **from GitHub Actions**. I assume that `192.168.176.3:9042` is not available for some reason from GitHub Actions engine in general.

**Comment by EduardoFLima** [comment]
Hey... no, it is not publicly available, it is a self-hosted runner.

Other github action is running a script which uses this very same cassandra instance and they are working fine. The result of the ping:
```
--- 192.168.80.3 ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
```
